# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TextFileImporter
                                 A QGIS plugin
 Data importer tool for Suedlink Project
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-09-28
        copyright            : (C) 2026 by Santiago Negrete
        email                : santiago_nsalazar@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TextFileImporter class from file TextFileImporter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .text_file_importer import TextFileImporter
    return TextFileImporter(iface)
