# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TextFileImporter
                                 A QGIS plugin
 Data importer tool for Suedlink Project
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-09-28
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Santiago Negrete
        email                : santiago_nsalazar@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QLocale, QTranslator, QCoreApplication
from qgis.core import QgsSettings
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Import the code for the dialog
from qgis.core import QgsProject, QgsVectorLayer
from .text_file_importer_dialog import TextFileImporterDialog
import os.path # for file path manipulations
import os # for path manipulations


class TextFileImporter:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Text File Importer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('TextFileImporter', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Text File Importer'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Text File Importer'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        if self.first_start:
            self.first_start = False
            self.dlg = TextFileImporterDialog()

        self.dlg.show() #show the dialog
        result = self.dlg.exec_()

        if result:
          
            file_path = self.dlg.filePath.text()
            
            if file_path:
                
                success = self.import_text_file(file_path)
                if success:
                    self.iface.messageBar().pushMessage(
                        "Success", "Text data successfully loaded as a spatial temporary layer!", level=0
                    )
                else:
                    self.iface.messageBar().pushMessage(
                        "Error", "Could not parse file structure or coordinate attributes.", level=2
                    )
            else:
                self.iface.messageBar().pushMessage(
                    "Warning", "No file selected. Please choose a valid path.", level=1
                )


    def import_text_file(self, file_path=None):

        if file_path is None or not os.path.exists(file_path):
            return False

        with open(file_path, 'r', encoding='utf-8') as f: 
            first_line = f.readline().strip()

        if ';' in first_line:
            delimiter = ';'
        elif ',' in first_line:
            delimiter = ','
        elif ' ' in first_line:
            delimiter = ' '
        else:
            delimiter = ';'  

        options = [
            f"delimiter={delimiter}",
            "xField=field_2",
            "yField=field_3",
            "crs=EPSG:25832",  
            "useHeader=No",    
            "geomType=Point"
        ]
        
       #Create a temporary table in QGIS
        clean_path = file_path.replace(os.sep, '/')
        # FIXED: Added [0] to extract just the string name from the tuple split layout
        base_name = os.path.splitext(os.path.basename(file_path))[0]
        layer_name = f"{base_name}_temporary"
        
        uri = f"file:///{clean_path}?{'&'.join(options)}"
        
        layer = QgsVectorLayer(uri, layer_name, "delimitedtext")
        
        if not layer.isValid():
            return False

        # --- OPTIONAL BONUS: RENAME COLUMNS TO PROFESSIONAL HEADERS ---
        field_mapping = {
            "field_1": "ID",
            "field_2": "X",
            "field_3": "Y",
            "field_4": "Z",
            "field_5": "Code",
            "field_6": "Stationing"
        }
        
        layer.startEditing()
        for idx, field in enumerate(layer.fields()):
            old_name = field.name()
            if old_name in field_mapping:
                layer.renameAttribute(idx, field_mapping[old_name])
        layer.commitChanges()

        # Load the newly created temporary layer onto the QGIS Map Canvas
        QgsProject.instance().addMapLayer(layer)
        return True