# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TextFileImporter
                                 A QGIS plugin
 Data importer tool for Suedlink Project
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-09-28
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Santiago Negrete
        email                : santiago_nsalazar@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QLocale, QTranslator, QCoreApplication
from qgis.core import QgsSettings
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Import the code for the dialog
from .text_file_importer_dialog import TextFileImporterDialog
import os.path # for file path manipulations
import os # for path manipulations


class TextFileImporter:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Text File Importer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('TextFileImporter', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Text File Importer'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Text File Importer'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = TextFileImporterDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            self.import_text_file()

    def import_text_file(self):
        """Reads the selected text file and creates a point layer from it."""
        from qgis.core import (
            QgsVectorLayer, QgsField, QgsFeature, QgsPointXY, QgsGeometry,
            QgsProject
        )
        from qgis.PyQt.QtCore import QVariant

        file_path = self.dlg.mQgsFileWidget_input.filePath()
        delimiter = self.dlg.comboBox_delimiter.currentText()
        skip_lines = self.dlg.spinBox_skipLines.value()
        crs = self.dlg.mQgsProjectionSelectionWidget_crs.crs()
        layer_name = self.dlg.lineEdit_layerName.text() or "Imported points"

        col_id = self.dlg.spinBox_colID.value()
        col_x = self.dlg.spinBox_colX.value()
        col_y = self.dlg.spinBox_colY.value()
        col_z = self.dlg.spinBox_colZ.value()
        col_code = self.dlg.spinBox_colCode.value()
        col_pk = self.dlg.spinBox_colPK.value()

        # Create memory layer with fields matching your data
        layer = QgsVectorLayer(f"PointZ?crs={crs.authid()}", layer_name, "memory")
        provider = layer.dataProvider()
        provider.addAttributes([
            QgsField("id", QVariant.String),
            QgsField("z", QVariant.Double),
            QgsField("code", QVariant.String),
            QgsField("pk", QVariant.String),
        ])
        layer.updateFields()

        with open(file_path, "r", encoding="utf-8") as f:
            lines = f.readlines()[skip_lines:]

        features = []
        for line in lines:
            line = line.strip()
            if not line:
                continue
            parts = line.split(delimiter if delimiter != "Tab" else "\t")
            try:
                pid = parts[col_id]
                x = float(parts[col_x])
                y = float(parts[col_y])
                z = float(parts[col_z])
                code = parts[col_code]
                pk = parts[col_pk]
            except (IndexError, ValueError):
                continue  # skip malformed lines

            feat = QgsFeature(layer.fields())
            feat.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(x, y)))
            feat.setAttributes([pid, z, code, pk])
            features.append(feat)

        provider.addFeatures(features)
        layer.updateExtents()
        QgsProject.instance().addMapLayer(layer)
        